### ISSUE TITLE
about 4.0 release

### ISSUE THREAD

**Issue by alexcorvi** [alexcorvi/apexo#135]
## About the next release

The 4.0 release will be the biggest release ever, fixing one of the hardest bugs and implementing new features that I'm sure you'll love.

It will also be the first release that has unit testing and E2E/integration testing. So less bugs are expected.

 - [x] Rewrite DB driver for more efficient and seamless synchronization between MobX stores and PouchDB.
 - [x] E2E testing using cypress.
 - [x] Unit testing.
 - [x] Improve performance using code-splitting.
 - [x] Local DB compression.
 - [x] Support iphone HEIC format.
 - [x] Redesign to a more contemporary web application.
 - [x] More things to click.
 - [x] Tabs on top of panels.
 - [x] Ability to add patient avatars.
 - [x] Setting lock to prevent unintentional changes.
 - [x] Less DB footprint.
 - [x] Supporting more languages.
 - [x] Improved hotlinking.
 - [x] Updated website and documentation.
 - [x] Better RTL support.
 - [x] better i18 system.
 - [x] Labs page.
 - [x] Update to the last release of fabric-ui.
 - [x] Fixing reported bugs in 3.0.
 - [x] Full backward compatibility.

Please note that because I'm working on this project alone, I'll stop fixing bugs and improving the 3.0 version until the 4.0 version comes out. And due to the size of the 4.0 release, this may take some time, but I'm doing my best, I promise!

Moreover, [here's the 4.0 branch](https://github.com/alexcorvi/apexo/tree/4.0) if you're so eager to test it.

**Comment by RiPPERD** [comment]
keep up the good work

**Comment by alexcorvi** [comment]
4.0 is finally out
