### ISSUE TITLE
New feature: Chat Bots

### ISSUE THREAD

**Issue by alexcorvi** [alexcorvi/apexo#179]
I'm thinking of implementing chat bots into the application, few options are available but I'm leaning to _Telegram_.

Currently, the application lacks:

1. A mechanism by which notifications are sent to doctors
2. An appointment booking functionality
3. Appointment reminders for the patient
4. Broadcasting promotions and offers from dentists to patients

I think _chat bots_ will fix those lacking features beautifully.

- **What do you think?**
- **What chat bot platform you think is more suitable?**
- **What other features you think chat bots can solve?**

----

### Todo list:

- [ ] Chat bot for doctor reminder and notifications
- [ ] Chat bot for appointment booking
- [ ] Chat bot for patient appointment reminder
- [ ] Promotional broadcasting, dentists to patients

**Comment by fcojaviergon** [comment]
i think that is really important keep in touch with the doctos and patients, email notification of appointment is useful, other feature could be the possibility to set a reminder schedule ex: this patient should come every 30 days.
Nice job with the app.

**Comment by RobertDaniel7** [comment]
This is the only feature Apexo misses for me.
This would be great and would make the app comprehensive. keep up the good work.
